---

- name: DNF Makecache 
  ansible.builtin.shell: dnf makecache 

- name: Speed up DNF
  ansible.builtin.shell: |
    sed -i 's/.*{{ item.option }}=.*//g' /etc/dnf/dnf.conf
    echo '{{ item.option }}={{ item.value }}' | tee -a /etc/dnf/dnf.conf
  loop:
    - { option: "max_parallel_downloads", value: "{{ dnf_max_parallel_downloads }}" }
    - { option: "fastestmirror", value: "{{ dnf_fastestmirror }}" }
  when: 

- name: Upgrade all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Install base packages 
  ansible.builtin.dnf:
    name:
      # System 
      - bluez 
      - bluez-tools 
      - cockpit 
      - cockpit-machines 
      - cockpit-ostree 
      - cockpit-podman 
      - cockpit-system 
      - dbus 
      - dbus-daemon 
      - dbus-tools 
      - dunst 
      - gnome-keyring 
      - gvfs-mtp 
      - grim 
      - jmtpfs 
      - lxpolkit 
      - man-pages 
      - openssh 
      - openssl 
      - papirus-icon-theme 
      - pipewire 
      - plocate 
      - polkit 
      - river 
      - river-bsp-layout 
      - rofi-wayland 
      - swaybg 
      - swayidle 
      - swaylock 
      - tailscale 
      - waybar 
      - wl-clipboard 
      - wlr-randr 
      - wireplumber 
      - xdg-desktop-portal-wlr 
      - xdg-user-dirs 
      - xorg-x11-server-Xwayland 
      - zsh 
      - zsh-autosuggestions 

      # Applications 
      - alacritty 
      - bc 
      - distrobox 
      - firefox 
      - keepassxc
      - libreoffice
      - nvtop 
      - openvpn 
      - pavucontrol 
      - playerctl 
      - ranger 
      - ripgrep 
      - thunar 
      - thunar-archive-plugin 
      - thunar-volman 
      - unzip 
      - vlc  
      - zip 

      # Fonts 
      - cascadia-code-fonts 
      - fontawesome-fonts 
      - google-noto-emoji-fonts  

      # Virtualization 
      - virt-install 
      - libvirt 
      - libvirt-daemon-config-network 
      - libvirt-daemon-kvm 
      - qemu-kvm 
      - virt-manager 
      - virt-viewer 
      - libguestfs-tools 
      - python3-libguestfs 
      - virt-top 

      # Development 
      - '@Development Tools' 
      - jq 
      - neovim 
      - nodejs 
      - python 
      - python3 
      - python3-pip 
      - rpmdevtools 
      - rpmlint 
      - rustup 
      - sqlite3 

      # Productivity
      - hledger 
      - krita 
      - libreoffice 

      # Recreation 
      - discord 
      - steam

      # Networking 
      - NetworkManager
      - NetworkManager-tui

    state: latest

- name: Autoremove unneeded packages 
  ansible.builtin.dnf: 
    autoremove: true

- name: Run rustup-init
  ansible.builtin.shell: rustup-init --default-host x86_64-unknown-linux-gnu --profile default --default-toolchain stable -y
  become: true 
  become_user: "{{ primary_user }}"
