---

- name: DNF Makecache 
  ansible.builtin.shell: dnf makecache 

- name: Upgrade all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Install base packages 
  ansible.builtin.dnf:
    name:
      # System 
      - ansible
      - bluez
      - bluez-tools
      - dbus 
      - dbus-daemon
      - dbus-tools
      - distrobox
      - dunst
      - gnome-keyring
      - gvfs-mtp
      - grim
      - grimshot
      - jmtpfs
      - lxpolkit
      - NetworkManager
      - NetworkManager-tui
      - openssh
      - openssl
      - papirus-icon-theme
      - pipewire
      - playerctl
      - polkit
      - river
      - river-bsp-layout
      - rofi-wayland
      - swaybg
      - swayidle
      - swaylock
      - tailscale
      - thunar
      - thunar-archive-plugin
      - thunar-volman
      - waybar
      - wireplumber
      - wl-clipboard
      - wlr-randr
      - xdg-desktop-portal-wlr
      - xdg-user-dirs
      - xorg-x11-server-Xwayland
      
      # Applications 
      - alacritty
      - firefox
      - hledger
      - keepassxc
      - kpcli
      - krita
      - libreoffice
      - neovim
      - openvpn
      - pavucontrol
      - ranger
      - ripgrep
      - torbrowser-launcher
      - unzip
      - vlc
      - zip

      # Fonts 
      - cascadia-code-pl-fonts
      - google-noto-emoji-fonts

      # Development 
      - "@Development Tools"
      - rpmdevtools
      - rpmlint
      - rustup

    state: latest

- name: Autoremove unneeded packages 
  ansible.builtin.dnf: 
    autoremove: true

- name: Run rustup-init
  ansible.builtin.shell: rustup-init --default-host x86_64-unknown-linux-gnu --profile default --default-toolchain stable -y
  become: true 
  become_user: "{{ primary_user }}"
