--- 

- name: Change hostname 
  ansible.builtin.hostname: 
    name: "{{ hostname }}"

- name: Enable Tailscaled
  ansible.builtin.systemd_service:
    name: tailscaled
    state: started
    enabled: true

- name: Enable libvirtd 
  ansible.builtin.systemd_service: 
    name: libvirtd 
    state: started 
    enabled: true 

- name: Enable plocate-updatedb 
  ansible.builtin.systemd_service: 
    name: plocate-updatedb.timer 
    state: started 
    enabled: true 
